name: Build and Test Maven Project

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
        - name: Checkout code
        - uses: actions/checkout@v3

        - name: Set up Java JDK
        uses: actions/setup-java@v3
        with:
            java-version: '11'  # Specify the Java version required by your project

        - name: Set up Maven
        uses: actions/setup-java@v3
        with:
                java-version: '11'
                maven-version: '3.8.6'  # Specify the Maven version required by your project

        - name: Build with Maven
        run: mvn clean install  # Run your Maven commands here

        - name: Run Tests
        run: mvn test
