on: push
jobs:
    first-job:
        runs-on: windows-latest
        steps:
            - run: node --version
            - run: npm --version
    second-job:
        runs-on: ubuntu-latest
        steps:
            - uses: Build with Maven
            - run: mvn clean install
            - run: mvn test